#' @importFrom purrr map
#' @importFrom rlang as_quosure
#' @importFrom stats formula
#' @importFrom fabletools model
#' @importFrom fabletools mable_vars
#' @importFrom dplyr full_join
#' @importFrom tsibble key_vars
#' @importFrom dplyr bind_rows
#' @importFrom fabletools mable
#' @importFrom purrr reduce
#' @importFrom tsibble measured_vars
#' @importFrom rlang sym
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom tsibble index_var
#' @importFrom purrr map2
#' @importFrom tsibble as_tibble
#' @importFrom dplyr bind_cols
#' @importFrom tsibble as_tsibble
#' @importFrom purrr map_lgl
#' @importFrom dplyr select
#' @importFrom stats fitted
#' @importFrom fable AR
#' @importFrom fable ARIMA
#' @importFrom fable CROSTON
#' @importFrom fable ETS
#' @importFrom fable MEAN
#' @importFrom fable NAIVE
#' @importFrom fable NNETAR
#' @importFrom fable RW
#' @importFrom fable SNAIVE
#' @importFrom fable THETA
#' @importFrom fable TSLM
#' @importFrom fable VAR
#' @importFrom purrr imap
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom fabletools forecast
#' @importFrom distributional dist_degenerate
#' @importFrom stats coef
#' @importFrom stats lm
#' @importFrom rlang abort
#' @importFrom tsibble key
#' @importFrom dplyr group_split
#' @importFrom dplyr distinct
#' @importFrom purrr possibly
#' @importFrom rlang f_lhs
#' @importFrom rlang f_rhs
#' @importFrom rlang eval_tidy
#' @importFrom rlang eval_bare
#' @importFrom purrr compact
#' @importFrom stats spec.ar
#' @importFrom stats na.contiguous
#' @importFrom stats as.ts
#' @importFrom stats frequency
#' @importFrom purrr map_dbl
#' @importFrom stats var
#' @importFrom stats Box.test
#' @importFrom stats median
#' @importFrom stats acf
#' @importFrom stats na.pass
#' @importFrom stats sd
#' @importFrom stats embed
#' @importFrom stats ts
#' @importFrom stats setNames
#' @importFrom rlang expr
#' @importFrom stats stl
#' @importFrom stats supsmu
#' @importFrom rlang list2
#' @importFrom rlang quo
#' @importFrom stats poly
#' @importFrom stats bw.nrd0
#' @importFrom stats dnorm
#' @importFrom slider slide_dbl
#' @importFrom purrr transpose
#' @importFrom purrr map2_dbl
#' @importFrom stats optimise
#' @importFrom rlang new_formula
#' @importFrom rlang enexpr
#' @importFrom stats na.omit
#' @importFrom distributional is_distribution
#' @importFrom purrr map_chr
#' @importFrom tsibble tibble
#' @importFrom dplyr filter
#' @importFrom fabletools new_specials
#' @importFrom rlang env
#' @importFrom rlang caller_env
#' @importFrom rlang enexprs
#' @importFrom rlang enquos
#' @importFrom rlang get_env
#' @importFrom purrr compose
#' @importFrom rlang is_empty
#' @importFrom rlang env_parents
#' @importFrom rlang base_env
#' @importFrom rlang call2
#' @importFrom stats model.frame
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
#' @importFrom rlang dots_list
#' @importFrom purrr partial
NULL
