#' @importFrom tsibble measured_vars
#' @importFrom tsibble key_vars
#' @importFrom dplyr group_by
#' @importFrom tsibble key
#' @importFrom dplyr group_split
#' @importFrom dplyr select
#' @importFrom furrr future_map
#' @importFrom dplyr bind_rows
#' @importFrom purrr map
#' @importFrom purrr possibly
#' @importFrom stats spec.ar
#' @importFrom stats na.contiguous
#' @importFrom stats as.ts
#' @importFrom stats frequency
#' @importFrom purrr map_dbl
#' @importFrom stats var
#' @importFrom tseries terasvirta.test
#' @importFrom fracdiff fracdiff
#' @importFrom urca ur.pp
#' @importFrom stats Box.test
#' @importFrom urca ur.kpss
#' @importFrom stats median
#' @importFrom stats acf
#' @importFrom stats na.pass
#' @importFrom stats sd
#' @importFrom stats embed
#' @importFrom stats lm
#' @importFrom stats ts
#' @importFrom Rcatch22 catch22_all
#' @importFrom stats setNames
#' @importFrom stats optimise
#' @importFrom purrr map_lgl
#' @importFrom rlang abort
#' @importFrom purrr map2
#' @importFrom magrittr set_names
#' @importFrom rlang eval_tidy
#' @importFrom rlang expr
#' @importFrom stats stl
#' @importFrom stats supsmu
#' @importFrom rlang list2
#' @importFrom rlang quo
#' @importFrom stats coef
#' @importFrom stats poly
#' @importFrom stats bw.nrd0
#' @importFrom stats dnorm
#' @importFrom slider slide_dbl
#' @importFrom purrr transpose
#' @importFrom purrr map2_dbl
#' @importFrom dplyr distinct
#' @importFrom purrr map_int
#' @importFrom dplyr filter
#' @importFrom tsibble build_tsibble
#' @importFrom fable AR
#' @importFrom rlang sym
#' @importFrom fabletools model
#' @importFrom fabletools forecast
#' @importFrom fable ARIMA
#' @importFrom fable SNAIVE
#' @importFrom fable RW
#' @importFrom fable THETA
#' @importFrom fable ETS
#' @importFrom fable NNETAR
#' @importFrom fable CROSTON
#' @importFrom fs dir_create
#' @importFrom qs qsave
#' @importFrom fabletools accuracy
#' @importFrom fable MEAN
#' @importFrom fable NAIVE
#' @importFrom fable TSLM
#' @importFrom fable VAR
#' @importFrom rlang f_lhs
#' @importFrom rlang f_rhs
#' @importFrom dplyr transmute
#' @importFrom rlang eval_bare
#' @importFrom fabletools new_specials
#' @importFrom rlang dots_list
#' @importFrom fabletools new_model_class
#' @importFrom tsibble is_regular
#' @importFrom fabletools new_model_definition
#' @importFrom rlang enquo
NULL
