#' Soothsayer model aliases
#'
#' @description A set of soothsayer model aliases (for purposes of matching).
#' @rdname soothsayer_model_aliases
#' @export
soothsayer_alias_set <- list( "fable::AR" = fable::AR,
                              "AR" = fable::AR,
                              "ar" = fable::AR,
                              "fable::ARIMA" = fable::ARIMA,
                              "ARIMA" = fable::ARIMA,
                              "arima" = fable::ARIMA,
                              "fable::CROSTON" = fable::CROSTON,
                              "CROSTON" = fable::CROSTON,
                              "croston" = fable::CROSTON,
                              "fable::ETS" = fable::ETS,
                              "ETS" = fable::ETS,
                              "ets" = fable::ETS,
                              "fable::MEAN" = fable::MEAN,
                              "MEAN" = fable::MEAN,
                              "mean" = fable::MEAN,
                              "fable::NAIVE" = fable::NAIVE,
                              "NAIVE" = fable::NAIVE,
                              "naive" = fable::NAIVE,
                              "fable::NNETAR" = fable::NNETAR,
                              "NNETAR" = fable::NNETAR,
                              "nnetar" = fable::NNETAR,
                              "fable::RW" = fable::RW,
                              "RW" = fable::RW,
                              "rw" = fable::RW,
                              "fable::SNAIVE" = fable::SNAIVE,
                              "SNAIVE" = fable::SNAIVE,
                              "snaive" = fable::SNAIVE,
                              "fable::THETA" = fable::THETA,
                              "THETA" = fable::THETA,
                              "theta" = fable::THETA,
                              "fable::TSLM" = fable::TSLM,
                              "TSLM" = fable::TSLM,
                              "tslm" = fable::TSLM,
                              "fable::VAR" = fable::VAR,
                              "VAR" = fable::VAR,
                              "var" = fable::VAR
)
